name: Run Daily Crawler

on:
  schedule:
    - cron: '0 9 * * *'   # UTC 09:00 = KST 18:00
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Psw98!!2
          MYSQL_DATABASE: kospi_sector_trend
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          MYSQL_HOST: mysql          # 서비스 이름
          MYSQL_PORT: 3306
          MYSQL_USER: root
          MYSQL_PASSWORD: Psw98!!2
          MYSQL_DB: kospi_sector_trend
        run: python src/crawler.py
